SET
    statement_timeout = 0;

SET
    lock_timeout = 0;

SET
    idle_in_transaction_session_timeout = 0;

SET
    client_encoding = 'UTF8';

SET
    standard_conforming_strings = on;

SELECT
    pg_catalog.set_config ('search_path', '', false);

SET
    check_function_bodies = false;

SET
    xmloption = content;

SET
    client_min_messages = warning;

SET
    row_security = off;

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql"
WITH
    SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"
WITH
    SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto"
WITH
    SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault"
WITH
    SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
WITH
    SCHEMA "extensions";

CREATE TYPE "public"."review_status" AS ENUM ('draft', 'pending', 'approved', 'rejected');

ALTER TYPE "public"."review_status" OWNER TO "postgres";

CREATE TYPE "public"."reward_level" AS ENUM ('college', 'university', 'provincial', 'national');

ALTER TYPE "public"."reward_level" OWNER TO "postgres";

CREATE TYPE "public"."reward_type" AS ENUM (
    'individual1st',
    'individual2nd',
    'individual3rd',
    'individual4th',
    'individual5th',
    'individual6th',
    'team1st',
    'team2nd',
    'team3rd'
);

ALTER TYPE "public"."reward_type" OWNER TO "postgres";

SET
    default_tablespace = '';

SET
    default_table_access_method = "heap";

CREATE TABLE
    IF NOT EXISTS "public"."activities" (
        "id" bigint NOT NULL,
        "created_at" timestamp
        with
            time zone DEFAULT "now" () NOT NULL,
            "title" "text" NOT NULL,
            "description" "text"
    );

ALTER TABLE "public"."activities" OWNER TO "postgres";

ALTER TABLE "public"."activities"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activities_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE
    IF NOT EXISTS "public"."application_awards" (
        "id" bigint NOT NULL,
        "application_id" bigint NOT NULL,
        "award_id" bigint NOT NULL
    );

ALTER TABLE "public"."application_awards" OWNER TO "postgres";

ALTER TABLE "public"."application_awards"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."application_awards_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE
    IF NOT EXISTS "public"."applications" (
        "id" bigint NOT NULL,
        "created_at" timestamp
        with
            time zone DEFAULT "now" () NOT NULL,
            "user_id" "uuid" NOT NULL,
            "activity_id" bigint NOT NULL,
            "status" "public"."review_status" NOT NULL,
            "description" "text"
    );

ALTER TABLE "public"."applications" OWNER TO "postgres";

ALTER TABLE "public"."applications"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."applications_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE
    IF NOT EXISTS "public"."awards" (
        "id" bigint NOT NULL,
        "created_at" timestamp
        with
            time zone DEFAULT "now" () NOT NULL,
            "user_id" "uuid" NOT NULL,
            "contest_id" bigint NOT NULL,
            "level" "public"."reward_level" NOT NULL,
            "status" "public"."review_status" NOT NULL,
            "description" "text"
    );

ALTER TABLE "public"."awards" OWNER TO "postgres";

CREATE TABLE
    IF NOT EXISTS "public"."contests" (
        "id" bigint NOT NULL,
        "created_at" timestamp
        with
            time zone DEFAULT "now" () NOT NULL,
            "title" "text" NOT NULL,
            "description" "text"
    );

ALTER TABLE "public"."contests" OWNER TO "postgres";

ALTER TABLE "public"."contests"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contests_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE
    IF NOT EXISTS "public"."notices" (
        "id" bigint NOT NULL,
        "created_at" timestamp
        with
            time zone DEFAULT "now" () NOT NULL,
            "title" "text" NOT NULL,
            "content" "text",
            "category" "text",
            "updated_at" timestamp without time zone DEFAULT "now" () NOT NULL
    );

ALTER TABLE "public"."notices" OWNER TO "postgres";

ALTER TABLE "public"."notices"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notices_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE "public"."awards"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rewards_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY "public"."activities" ADD CONSTRAINT "activities_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."application_awards" ADD CONSTRAINT "application_awards_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."applications" ADD CONSTRAINT "applications_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."contests" ADD CONSTRAINT "contests_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."notices" ADD CONSTRAINT "notices_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."awards" ADD CONSTRAINT "rewards_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."application_awards" ADD CONSTRAINT "application_awards_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "public"."applications" ("id");

ALTER TABLE ONLY "public"."application_awards" ADD CONSTRAINT "application_awards_award_id_fkey" FOREIGN KEY ("award_id") REFERENCES "public"."awards" ("id");

ALTER TABLE ONLY "public"."applications" ADD CONSTRAINT "applications_activity_id_fkey" FOREIGN KEY ("activity_id") REFERENCES "public"."activities" ("id");

ALTER TABLE ONLY "public"."applications" ADD CONSTRAINT "applications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id");

ALTER TABLE ONLY "public"."awards" ADD CONSTRAINT "rewards_contest_id_fkey" FOREIGN KEY ("contest_id") REFERENCES "public"."contests" ("id");

ALTER TABLE ONLY "public"."awards" ADD CONSTRAINT "rewards_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id");

ALTER TABLE "public"."activities" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."application_awards" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."applications" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."awards" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."contests" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."notices" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "anon";

GRANT USAGE ON SCHEMA "public" TO "authenticated";

GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."activities" TO "anon";

GRANT ALL ON TABLE "public"."activities" TO "authenticated";

GRANT ALL ON TABLE "public"."activities" TO "service_role";

GRANT ALL ON SEQUENCE "public"."activities_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."activities_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."activities_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."application_awards" TO "anon";

GRANT ALL ON TABLE "public"."application_awards" TO "authenticated";

GRANT ALL ON TABLE "public"."application_awards" TO "service_role";

GRANT ALL ON SEQUENCE "public"."application_awards_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."application_awards_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."application_awards_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."applications" TO "anon";

GRANT ALL ON TABLE "public"."applications" TO "authenticated";

GRANT ALL ON TABLE "public"."applications" TO "service_role";

GRANT ALL ON SEQUENCE "public"."applications_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."applications_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."applications_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."awards" TO "anon";

GRANT ALL ON TABLE "public"."awards" TO "authenticated";

GRANT ALL ON TABLE "public"."awards" TO "service_role";

GRANT ALL ON TABLE "public"."contests" TO "anon";

GRANT ALL ON TABLE "public"."contests" TO "authenticated";

GRANT ALL ON TABLE "public"."contests" TO "service_role";

GRANT ALL ON SEQUENCE "public"."contests_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."contests_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."contests_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."notices" TO "anon";

GRANT ALL ON TABLE "public"."notices" TO "authenticated";

GRANT ALL ON TABLE "public"."notices" TO "service_role";

GRANT ALL ON SEQUENCE "public"."notices_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."notices_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."notices_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."rewards_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."rewards_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."rewards_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";